apiVersion: apps/v1
kind: Deployment
metadata:
  name: besthospital1
  labels:
    app: besthospital1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: besthospital1
  template:
    metadata:
      labels:
        app: besthospital1
    spec:
      containers:
name: besthospital1
          image: docker-jfrog-testing/test:v1   # Replace with actual image if different
          ports:
containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: besthospital1-service
  labels:
    app: besthospital1
spec:
  selector:
    app: besthospital1
  ports:
protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
