apiVersion: apps/v1
kind: Deployment
metadata:
  name: besthospital1
  labels:
    app: besthospital1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: besthospital1
  template:
    metadata:
      labels:
        app: besthospital1
    spec:
      containers:
        - name: besthospital1
          image: nginx:latest
          ports:
            - containerPort: 80
